name: Update seasonal SVG

on:
  schedule:
    - cron: "0 2 * * *"   # ogni giorno 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate seasonal SVG
        run: node scripts/generate_name_svg.js

      - name: Commit changes (if any)
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/name.svg
          git commit -m "chore: refresh seasonal SVG ($(date -u +'%Y-%m-%d'))"
          git push
